DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Attendance;
DROP TABLE IF EXISTS Forms;



CREATE TABLE Users (
    ID STRING FOREIGN KEY UNIQUE NOT NULL,
    Role STRING NOT NULL,
    FirstName STRING NOT NULL,
    LastName STRING NOT NULL,
    Email STRING NOT NULL,
    Phone STRING
);

CREATE TABLE Attendance (
    usersID STRING FOREIGN KEY UNIQUE NOT NULL,
    formsID INTEGER FOREIGN KEY UNIQUE NOT NULL
);

CREATE TABLE Forms (
    ID INTEGER FOREIGN KEY UNIQUE NOT NULL,
    Name STRING NOT NULL,
    SitePath STRING NOT NULL
);